SWIDEA_SITE/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.home, name="home"),
    path('create', views.create, name="create"),
    path('post/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('dev', views.dev, name="dev"),
    path('dev_create', views.dev_create, name="dev_create"),
    path('tool/<int:id>', views.dev_detail, name="dev_detail"),
    path('dev_update/<int:id>', views.dev_update, name="dev_update"),
    path('dev_delete/<int:id>', views.dev_delete, name="dev_delete"),
]

SWIDEA_SITE/posts/models.py
import django
from django.db import models
from django.utils import timezone
# Create your models here.

class Tool(models.Model):
    name = models.CharField(blank=True, max_length=20, verbose_name="툴이름")
    type = models.CharField(blank=True, max_length=20, verbose_name="툴종류")
    content = models.TextField(blank=True, verbose_name="툴설명")

class Post(models.Model):
    title = models.CharField(blank=True,verbose_name ="제목", max_length=50)
    image = models.ImageField(blank=True, verbose_name ="이미지", upload_to='posts/%Y%m%d', height_field=None, width_field=None, max_length=None)
    content = models.TextField(blank=True,verbose_name ="내용")
    interest = models.CharField(blank=True,verbose_name ="관심도", max_length=50)
    devtool = models.ForeignKey(Tool, on_delete=models.CASCADE, related_name="post_tool", blank=True)    
    created_at = models.DateTimeField(blank=True,auto_now_add=True)
    updated_at = models.DateTimeField(blank=True,auto_now=True)

# class IdeaStar(models.Model):
#     post = models.ManyToManyField(
#         "post.Post",
#         related_name="list",
#         blank=True,
#     )
#     def count_posts(self):
#         return self.post.count()

SWIDEA_SITE/posts/views.py
from django.shortcuts import redirect, render
from .models import Post, Tool

#home
def home(request):
    posts = Post.objects.all()
    
    sort = request.GET.get('sort', 'None')
    if sort == "name":
       posts = posts.order_by("title")
    elif sort == "createAt":
       posts = posts.order_by("created_at")
    elif sort == "updateAt":
       posts = posts.order_by("-updated_at")

    context = {
        "posts":posts
    }
    return render(request, template_name = "posts/home.html", context=context)

#Create
def create(request):
    tools = Tool.objects.all()
    if request.method == "POST":
        title = request.POST["title"]
        image = request.FILES["image"]
        content = request.POST["content"]
        interest = request.POST["interest"]
        devtool = request.POST["devtool"]
        for tool in tools:
            if tool.name == devtool:
                devtool = tool
    
        Post.objects.create(title=title, image=image, content=content, interest=interest, devtool=devtool)

        return redirect('/')

    TOOL_LIST = []
    for tool in tools:
        TOOL_LIST.append(tool.name)
    
    context = {'tool_list':TOOL_LIST}
    return render(request, template_name='posts/create.html', context=context)

def detail(request, id):
    post = Post.objects.get(id=id)
    
    context = {
        "post": post,
    }
    
    return render(request, template_name='posts/detail.html', context=context)

# Update
def update(request, id):
    tools = Tool.objects.all()
    TOOL_LIST = []
    for tool in tools:
        TOOL_LIST.append(tool.name)

    if request.method == "POST":
        title = request.POST["title"]
        image = request.FILES["image"]
        content = request.POST["content"]
        interest = request.POST["interest"]
        devtool = request.POST["devtool"]
        for tool in tools:
            if tool.name == devtool:
                devtool = tool
        
        Post.objects.filter(id=id).update(title = title, image=image, content=content, interest=interest, devtool=devtool)
        return redirect(f"/post/{id}")
        
    elif request.method == "GET":
        post = Post.objects.get(id=id)
        context = {
            "post": post,
            "tool_list":TOOL_LIST
        }
        return render(request, template_name='posts/update.html', context=context)

# Delete
def delete(request, id):
    if request.method == "POST":
        Post.objects.filter(id=id).delete()
        return redirect('/')
    
# home2
def dev(request):
    tools = Tool.objects.all()
    
    context = {
        "tools":tools
    }
    return render(request, template_name = "posts/dev.html", context=context)

# Create2
def dev_create(request):
    if request.method == "POST":
        name = request.POST["name"]
        type = request.POST["type"]
        content = request.POST["content"]
        
        Tool.objects.create(name=name, type=type, content=content)
        
        return redirect('/dev')

    context = {}
    return render(request, template_name='posts/dev_create.html', context=context)

def dev_detail(request, id):
    tool = Tool.objects.get(id=id)
    
    all_post = tool.post_tool.all()
    
    context = {
        "tool":tool,
        "all_post":all_post,
    }
    
    return render(request, template_name='posts/dev_detail.html', context=context)

# Update2
def dev_update(request, id):
    if request.method == "POST":
        name = request.POST["name"]
        type = request.POST["type"]
        content = request.POST["content"]
        
        Tool.objects.filter(id=id).update(name = name, type=type, content=content)
        return redirect(f"/tool/{id}")
        
    elif request.method == "GET":
        tool = Tool.objects.get(id=id)
        context = {
            "tool": tool
        }
    
    return render(request, template_name='posts/dev_update.html', context=context)

# Delete
def dev_delete(request, id):
    if request.method == "POST":
        Tool.objects.filter(id=id).delete()
        return redirect('/dev')

SWIDEA_SITE/posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <div>
      <h1>Idea Register</h1>
      <div>
        아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!
      </div>
    </div>
    <form
      action="{% url 'posts:create' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div>
        <div>아이디어명:</div>
        <input type="text" name="title" />
      </div>
      <div>
        <div>Image:</div>
        <input type="file" name="image" />
      </div>
      <div>
        <div>아이디어 설명:</div>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
      </div>
      <div>
        <div>아이디어 관심도:</div>
        <input type="number" name="interest" />
      </div>
      <div>예상 개발툴:</div>
      <select name="devtool" id="">
        {% for tool in tool_list %}
        <option value="{{ tool }}">{{ tool }}</option>
        {% endfor %}
      </select>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>

    <a href="{% url 'posts:home' %}">Home</a>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>상세화면</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <article>
      {% if post.image %}
      <p>
        <img src="{{ post.image.url }}" alt="" />
      </p>
      {% endif %}
      <h2>제목 : {{ post.title }}</h2>
      <div>1) 아이디어 관심도 <br />{{post.interest}}</div>
      <div>
        2) 예상 개발 툴 <br /><a
          href="{% url 'posts:dev_detail' post.devtool.id %}"
          >{{post.devtool.name}}</a
        >
      </div>
      <div>3) 아이디어 설명 <br />{{post.content}}</div>
    </article>

    <div><a href="{% url 'posts:update' post.id %}">update</a></div>
    <form action="{% url 'posts:delete' post.id %}" method="post">
      {% csrf_token %}
      <button>삭제</button>
    </form>
    <div><a href="{% url 'posts:home' %}">Home</a></div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 관리</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    {% for tool in tools %}
    <article>
      <a href="{% url 'posts:dev_detail' tool.id %}">{{tool.name}}</a>
      <p>{{tool.type}}</p>
      <p>{{tool.content}}</p>
    </article>
    {% endfor %}
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_create.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <div>
      <h1>Idea Register</h1>
      <div>
        아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!
      </div>
    </div>
    <form
      action="{% url 'posts:dev_create' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div>
        <div>이름:</div>
        <input type="text" name="name" />
      </div>
      <div>
        <div>종류:</div>
        <input type="text" name="type" />
      </div>
      <div>
        <div>아이디어 설명:</div>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
      </div>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>

    <a href="{% url 'posts:dev' %}">DevHome</a>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_detail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>상세화면</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <article>
      <h2>{{ tool.name }}</h2>
      <div>{{tool.type}}</div>
      <div>{{tool.content}}</div>
      <hr />
      <div>만들 수 있는 SW 목록</div>
      {% for post in all_post %}
      <div><a href="{% url 'posts:detail' post.id %}">{{post.title}}</a></div>
      {% endfor %}
    </article>
    <div><a href="{% url 'posts:dev_update' tool.id %}">update</a></div>
    <form action="{% url 'posts:dev_delete' tool.id %}" method="post">
      {% csrf_token %}
      <button>삭제</button>
    </form>
    <div><a href="{% url 'posts:dev' %}">목록</a></div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_update.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 관리</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <form
      action="{% url 'posts:dev_update' tool.id %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div>
        <div>이름:</div>
        <input type="text" name="name" value="{{tool.name}}" />
      </div>
      <div>
        <div>종류:</div>
        <input type="text" name="type" value="{{tool.type}}" />
      </div>
      <div>
        <div>아이디어 설명:</div>
        <textarea name="content" id="" cols="30" rows="10">
{{tool.content}}</textarea
        >
      </div>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/home.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>홈 화면</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <div>
      <h1>Idea List</h1>
      <div>나의 아이디어를 잊지 말고 기록해보세요</div>
    </div>
    <form action="" method="GET">
      {% csrf_token %}
      <select id="sort" name="sort" onchange="this.form.submit();">
        <option value="none">--정렬기준--</option>
        <option value="star">찜하기순</option>
        <option value="name">이름순</option>
        <option value="createAt">등록순</option>
        <option value="updateAt">최신순</option>
      </select>
    </form>

    {% for post in posts %}
    <article>
      <div>
        <img src="{{ post.image.url }}" alt="" />
      </div>
      <a href="{% url 'posts:detail' post.id %}">
        <h1>{{post.title}}</h1>
      </a>
      <p>예상 개발 툴 : {{post.devtool.name}}</p>
      <p>아이디어 관심도 : {{post.interest}}</p>
    </article>
    {% endfor %}
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/update.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="/">아이디어 관리</a>
      <a href="{% url 'posts:dev' %}">개발툴 관리</a>
      <a href="{% url 'posts:dev_create' %}">개발툴 등록</a>
    </header>
    <form action="/update/{{post.id}}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
        아이디어명:
        <br />
        <input type="text" name="title" value="{{post.title}}" />
      </p>
      아이디어 설명:
      <br />
      <textarea name="content" id="" cols="30" rows="10">
{{post.content}}</textarea
      >
      <p>
        Image:
        <br />
        <div>Currently: {{ post.image.url }}</div>
        <div>Change: <input type="file" name="image" /></div>
      </p>
      <p>
        아이디어 관심도:
        <br />
        <input type="text" name="interest" value="{{post.interest}}" />
      </p>
      <p>
        예상 개발툴:
        <br />
        <select name="devtool" id="">
            {% for tool in tool_list %}
            <option value="{{ tool }}">{{ tool }}</option>
            {% endfor %}
          </select>
      </p>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="/">Home</a>
  </body>
</html>